### ISSUE TITLE
Loading pre-trained BERT

### ISSUE THREAD

**Issue by astariul** [kpot/keras-transformer#1]
Does your code support loading a pre-trained version of BERT, in order to use it for fine-tuning ?

**Comment by kpot** [comment]
If you're talking about [the models published by Google](https://github.com/google-research/bert#pre-trained-models) - then the answer is no, out of the box it doesn't. This should be possible in theory. However, Google admits those models have quite high demands for GPU/TPU RAM, which I simply don't have. So fine-tuning any of those was impractical for me so far.
