### ISSUE TITLE
what are the input for a language model?

### ISSUE THREAD

**Issue by pkumdl** [kpot/keras-transformer#15]
Hello:
Very nice code. I am trying to train my own language model using gpt. A language model, as the paper "all you need is attention" said, is built by predicting the next word with all their previous words. But I found that the input of your gpt model are not like that.
For exampke: if I have a sentence: [5,242,5,6,354], I suppose the input x should be [5],[5,242],[5,242,5],[5,242,5,6], and y should be [[242],[5],[6],[354]]; But the input  x in your model is [5,242,5,6,354], and y is [[242],[5],[6],[354]], and I could not found any dimension or reshape of x in your code. 
Could you please explain this differance? Thank you

**Comment by kpot** [comment]
Hi!
Your assumption about the input is wrong. Learning to predict the next character/word doesn't mean we have to do this by increasing the length of the sequence piece by piece. It can be done all at once. 
It's a common practice you will find everywhere. I'm sorry, but I can't explain this better than in thousands of articles, papers, educational channels and ML courses you can easily find. For example, check on [this course](https://www.coursera.org/learn/nlp-sequence-models) (you can also [find some of these videos on youtube](https://www.youtube.com/watch?v=_i3aqgKVNQI&index=2&list=PLkDaE6sCZn6F6wUI9tvS_Gw1vaFAx6rd6)). The course has everything you need to know both on sequence modelling and how to generate new sentences using already pre-trained model.

**Comment by alsm168** [comment]
@pkumdl In the procedure of training，the input should be the all sentence，when you use the trained model in perdiction, you should input the word one by one.
