### ISSUE TITLE
How to generate text use the trained model

### ISSUE THREAD

**Issue by pkumdl** [kpot/keras-transformer#16]
Hello:
I appreciate your code, because it is easy-reading. But I don't know how to generate text with the trained model, I only know how to evaluate the trained accuracy. So could you please tell me , thank you.

**Comment by kpot** [comment]
Hi!
It's a big topic and I'm a bad teacher. So, I can only give the same advice as in #15 - you need to read articles on beam search in application to language modeling. Beam search is not the only way of doing it, but perhaps the most popular one. Its application to the transformer is no different from any other similar model, whether it's built on LSTM, CNN or anything else.
