### ISSUE TITLE
multi-head behaviour

### ISSUE THREAD

**Issue by IbrH** [kpot/keras-transformer#17]
According to the "attention is all you need" paper, each head performs attention over the entire set of queries, keys and values, but with their own personal weights. Your implementation divides the last dimension over the heads. Why?

**Comment by gregory112** [comment]
I wish to know this too, so why did you close the issue? What is the solution??

**Comment by alsm168** [comment]
this is another solution of paper

**Comment by IbrH** [comment]
I closed it because the implementation isn't wrong at this part. Quote from the paper:
![grafik](https://user-images.githubusercontent.com/26464584/64254202-357f9400-cf1f-11e9-9e1f-8903ad41b41f.png)

**Comment by gregory112** [comment]
Yea after I read that sentence over and over again I finally understood what it means. The paper also say that each head attends to "representation subspaces", that's what confused me back then.
