### ISSUE TITLE
ImportError: cannot import name 'Activations' on GPT example

### ISSUE THREAD

**Issue by beau101023** [kpot/keras-transformer#26]
I followed the installation instructions on the readme, using Tensorflow as the backend, but trying to run the GPT example gives this error:

```Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/beau101023/transformer_project/keras-transformer/example/run_gpt.py", line 18, in <module>
    from .models import (
  File "/home/beau101023/transformer_project/keras-transformer/example/models.py", line 9, in <module>
    from keras_transformer.transformer import TransformerACT, TransformerBlock
  File "/home/beau101023/transformer_project/keras-transformer/keras_transformer/transformer.py", line 9, in <module>
    from keras.layers import Layer, Add, activations, Dropout
ImportError: cannot import name 'activations'
```
I am running this on a ubuntu 18.04 LTS instance in virtualbox, Python version 3.6.8, in a virtual environment.

Running `python -m example.run_gpt --help` gives the same error.

**Comment by zxk19981227** [comment]
I also met this question and i found it's only caused by a small chages between keras 1.11 and 1.12. If you don't mind the activations i think you chang hte 

> I followed the installation instructions on the readme, using Tensorflow as the backend, but trying to run the GPT example gives this error:
> 
> ```
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/beau101023/transformer_project/keras-transformer/example/run_gpt.py", line 18, in <module>
>     from .models import (
>   File "/home/beau101023/transformer_project/keras-transformer/example/models.py", line 9, in <module>
>     from keras_transformer.transformer import TransformerACT, TransformerBlock
>   File "/home/beau101023/transformer_project/keras-transformer/keras_transformer/transformer.py", line 9, in <module>
>     from keras.layers import Layer, Add, activations, Dropout
> ImportError: cannot import name 'activations'
> ```
> 
> I am running this on a ubuntu 18.04 LTS instance in virtualbox, Python version 3.6.8, in a virtual environment.
> 
> Running `python -m example.run_gpt --help` gives the same error.

I also met this question and i found it's only caused by a small chages between keras 1.11 and 1.12. If you don't mind the activations i think you import any activation as activations and reset the usage.

**Comment by l8doku** [comment]
I changed
```
from keras.layers import Layer, Add, activations, Dropout
```
to
```
from keras.layers import Layer, Add, Dropout
from keras import activations
```
and it worked for me. Not sure if this is the correct way of doing things.

**Comment by beau101023** [comment]
That solved the problem for me, thanks!
