### ISSUE TITLE
 bug in TransformerACT

### ISSUE THREAD

**Issue by GlassyWing** [kpot/keras-transformer#3]
```
    def initialize_control_tensors(self, halting):
        self.zeros_like_halting = K.zeros_like(
            halting, name='zeros_like_halting')
        self.ones_like_halting = K.ones_like(
            halting, name='ones_like_halting')
        self.remainder = self.zeros_like_halting    # <----- When `remainder` changes, which will also change `zeros_like_halting`.
        self.active_steps = self.ones_like_halting  # <----- 
        self.halt_budget = self.ones_like_halting - self.halt_epsilon
```

This problem makes training unstable or impossible.

**Comment by alsm168** [comment]
Hi  @GlassyWing I have a question: How does the ACT reduce the step？I feel the ACT can not reduce the step in universal transformer

**Comment by GlassyWing** [comment]
” Instead of deciding to run for a discrete number of steps, we have an attention distribution over the number of steps to run. “，You can learn more information from `Adaptive Computation Time` in [Attention and Augmented Recurrent Neural Networks](https://distill.pub/2016/augmented-rnns/#citation),

**Comment by alsm168** [comment]
@GlassyWing Thanks for your advice
