### ISSUE TITLE
Wrong predictions when reloading model

### ISSUE THREAD

**Issue by Andreasksalk** [kpot/keras-transformer#32]
Hello, 

Thanks for the easy implementation! 

I have problems reloading the model and using it for a production style pipeline.
I can clearly see through training and development that the models learns and gets better, but once i reload the model the predictions are gibberish. 

`model = load_model('model.h5', custom_objects={'TransformerCoordinateEmbedding': TransformerCoordinateEmbedding})`

Anyone else encountering these problems? 

Regards
Andreas

**Comment by Andreasksalk** [comment]
It only asks for TransformerCoordinateEmbedding and not TransformerBlock, and including this does not help. The model is saved with ModelCheckpoint(path, monitor='val_acc', save_best_only=True)

I use Keras 2.2.4 and Tensorflow 1.14. 

If you need anything else i would be glad to give these to any extend i can, however the complete code or model is out of limits because of NDA.

Regards
Andreas

**Comment by Andreasksalk** [comment]
Update: you do not need to create custom objects, this is done when loading the packages from import. However the keras_transformer.position has an error in the bottom:

```
get_custom_objects().update({
    'TransformerCoordinateEmbedding': TransformerCoordinateEmbedding,
    'AddCoordinateEncoding': AddCoordinateEncoding,
    'AddPositionalEncoding': AddCoordinateEncoding,
})
```

Needs to be changed to: 
```
get_custom_objects().update({
    'TransformerCoordinateEmbedding': TransformerCoordinateEmbedding,
    'AddCoordinateEncoding': AddCoordinateEncoding,
    'AddPositionalEncoding': AddPositionalEncoding,
})
```

As stated by others. However, this would only be needed if you use AddPositionalEncoding.

To the fix of my problem. It seems Keras 2.2.4 has a problem loading models, upgrading to Keras 2.3.1 fixed this problem. 

If you upgrade the keras_transformer.transformer needs to be updated. Activations is no longer part of keras.layers but keras. The following code needs to be changed from:

```
from keras.layers import Layer, Add, activations, Dropout
from keras import initializers
```

To:

```
from keras.layers import Layer, Add, Dropout
from keras import initializers, activations
```

I am closing this issue for now, since it i cant figure out whether this is a Keras or Keras_transformer issue, and version 2.2.4 is depricated. 

Regards
Andreas

**Comment by kpot** [comment]
Hi Andreas,
I'm currently working on porting the library to the new TF 2.x-based Keras API. Most of it is already working, although I still have some troubles with eager execution. I hope to publish the result in about a week.
