### ISSUE TITLE
Transformer encoder layer instead of Bidirectional LSTM

### ISSUE THREAD

**Issue by Eugen2525** [kpot/keras-transformer#5]
So I want to change below Keras bidirectional LSTM layer into Transformer encoder:

`lstmLayer = keras.layers.Bidirectional(
					keras.layers.CuDNNLSTM(args.rnnSize,
						return_sequences = True,
						recurrent_initializer = 'glorot_uniform'
					)
				)(inputLayer)`

so can this be accomplished using your library? The rest of the code remains same, I just want to replace bidirectional LSTM layers with Transformer.

I would really appreciate your help. Thanks.

**Comment by kpot** [comment]
Hi, you would need something like this

```python
transformer_input = <whatever you need>
transformer_depth = 5

transformer_block = TransformerBlock(
    name='transformer',
    num_heads=8,
    residual_dropout=0.1,
    attention_dropout=0.1,
    use_masking=False)
add_coordinate_embedding = TransformerCoordinateEmbedding(
    transformer_depth,
    name='coordinate_embedding')

transformer_output = transformer_input  # shape: (batch_size, sequence_length, input_size)
for step in range(transformer_depth):
    transformer_output = transformer_block(
        add_coordinate_embedding(transformer_output, step=step))

```

Please note that I set `use_masking` to `False`, allowing the attention to look "forward in time". This turns such Transformer into a rough (better) equivalent of a bi-directional LSTM in terms of the information flow.

**Comment by Eugen2525** [comment]
Thanks, this seems to work but I have not checked as I could not use my program with python 3.

I upvote for python 2 version of your program.

thanks.

**Comment by kpot** [comment]
Hi,

These days Python 2 is [considered dead](https://wiki.python.org/moin/Python2orPython3) by the community. All major libraries have either already dropped its support or are about to do that. If you're working on some project implemented in python2, you should consider transitioning it to Python 3. At least, you can start writing new code in python3-compatible style, and switch to python3 completely for new isolated components (such as micro-services).

I'm closing the ticket.
